export const ALLOWED_IMAGES_MIME_TYPE = [
  "image/jpeg",
  "image/jpg",
  "image/png",
  "image/gif",
  "image/svg+xml",
  "image/bmp",
  "image/webp",
  "image/x-icon",
  "image/tiff",
  "image/heif",
  "image/heic",
  "image/vnd.adobe.photoshop",
  "image/x-xcf",
  "image/x-portable-pixmap",
  "image/x-portable-graymap",
  "image/x-portable-bitmap",
  "image/vnd.ms-dds",
  "image/jp2",
  "image/apng",
  "image/cgm",
  "image/x-pict",
  "image/x-pcx",
  "image/x-targa",
  "image/vnd.adobe.illustrator",
  "image/x-exr",
  "image/vnd.dwg",
  "image/vnd.dxf",
];

export const MAX_FILE_SIZE = 5 * 1024 * 1024;
